Feature/142 assign roles review
bristol-su/assign-roles pull request #13
Opened 2021-02-03 15:05 UTC by AidanLaycock

2021-02-04 19:18 UTC, tobytwigger commented
@AidanLaycock This is amazing, it's such an improvement! Literally my only comment is that, when adding a new role, the role title should change if the position changes. Possibly in a watcher (there may be a better way), if the text in role title matches the old position, then set it to the newly selected position

2021-02-07 14:30 UTC, tobytwigger requested changes
Minor minor bug I spotted, other than that this is ready for merge!

2021-02-07 14:30 UTC, tobytwigger commented on public/modules/assign-roles/js/module.js
> +      return this.role_name === null || this.role_name === this.getPositionName(oldVal) ? this.role_name = this.getPositionName(newVal) : '';
Can we also check if the role name is ''? If you click in the role name box before changing the position, it doesn't change as `this.role_name` = '' not null

2021-02-07 14:30 UTC, tobytwigger commented on resources/js/components/participant/AddRoleForm.vue
> +                // If role name is empty or hasn't been changed then assign Position Name
Same here.

2021-02-08 08:15 UTC, AidanLaycock commented
@tobytwigger - Both of the above issues should be resolved. I've refactored it to incorporate Null/falsey Values.

2021-02-10 11:15 UTC, tobytwigger approved these changes

2021-02-10 11:15 UTC, merged